"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "artists",
      [
        {
          firstName: "Tommaso",
          lastName: "di Ser Giovanni di Simone",
          knownAs: "Masaccio",
          bornOn: 1401,
          diedOn: 1428,
          gender: "male",
          placeOfBirth: "San Giovanni Valdarno",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "Chiesa di Santa Maria del Carmine, Florence",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Masaccio",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Donato",
          lastName: "di Niccolò di Betto Bardi",
          knownAs: "Donatello",
          bornOn: 1386,
          diedOn: 1466,
          gender: "male",
          placeOfBirth: "Florence",
          placeOfDeath: "Florence",
          nationality: "Italian",
          burialSite: "Basilica di San Lorenzo, Florence",
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Donatello",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jan",
          lastName: "van Eyck",
          knownAs: null,
          bornOn: 1395,
          diedOn: 1441,
          gender: "male",
          placeOfBirth: "Maaseik",
          placeOfDeath: "Bruges",
          nationality: "Flemish",
          burialSite: "St. Donatian's Cathedral, Bruges",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jan_van_Eyck",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Rogier",
          lastName: "van der Weyden",
          knownAs: null,
          bornOn: 1399,
          diedOn: 1464,
          gender: "male",
          placeOfBirth: "Tournai",
          placeOfDeath: "Brussels",
          nationality: "Flemish",
          burialSite: "St Michael and St Gudula Cathedral, Brussels",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Rogier_van_der_Weyden",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Dieric",
          lastName: "Bouts",
          knownAs: null,
          bornOn: 1415,
          diedOn: 1475,
          gender: "male",
          placeOfBirth: "Haarlem",
          placeOfDeath: "Leuven",
          nationality: "Flemish",
          burialSite: "Franciscan church of Leuven",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Dieric_Bouts",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Alessandro",
          lastName: "di Mariano di Vanni Filipepi",
          knownAs: "Sandro Botticelli",
          bornOn: 1445,
          diedOn: 1510,
          gender: "male",
          placeOfBirth: "Florence",
          placeOfDeath: "Florence",
          nationality: "Italian",
          burialSite: "Chiesa di San Salvatore in Ognissanti, Florence",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Sandro_Botticelli",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hugo",
          lastName: "van der Goes",
          knownAs: null,
          bornOn: 1430,
          diedOn: 1482,
          gender: "male",
          placeOfBirth: "Ghent",
          placeOfDeath: "Auderghem",
          nationality: "Flemish",
          burialSite: "Red Cloister, Brussels",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Hugo_van_der_Goes",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Leonardo",
          lastName: "di ser Piero da Vinci",
          knownAs: "Leonardo da Vinci",
          bornOn: 1452,
          diedOn: 1519,
          gender: "male",
          placeOfBirth: "Vinci",
          placeOfDeath: "Amboise",
          nationality: "Italian",
          burialSite: "Chapel of Saint-Hubert, Amboise",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Leonardo_da_Vinci",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Michelangelo",
          lastName: "di Lodovico Buonarroti Simoni",
          knownAs: "Michelangelo",
          bornOn: 1475,
          diedOn: 1564,
          gender: "male",
          placeOfBirth: "Caprese",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "Basilica of Santa Croce, Florence",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Michelangelo",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Raffaello",
          lastName: "Sanzio da Urbino",
          knownAs: "Raphael",
          bornOn: 1483,
          diedOn: 1520,
          gender: "male",
          placeOfBirth: "Urbino",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "Pantheon, Rome",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Raphael",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Giovanni",
          lastName: "Bellini",
          knownAs: null,
          bornOn: 1430,
          diedOn: 1516,
          gender: "male",
          placeOfBirth: "Venice",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Basilica di San Giovanni e Paolo, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Giovanni_Bellini",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Giorgio",
          lastName: "Barbarelli da Castelfranco",
          knownAs: "Giorgione",
          bornOn: 1477,
          diedOn: 1510,
          gender: "male",
          placeOfBirth: "Castelfranco Veneto",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Island of Poveglia(?), Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Giorgione",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Tiziano",
          lastName: "Vecelli",
          knownAs: "Titian",
          bornOn: 1488,
          diedOn: 1576,
          gender: "male",
          placeOfBirth: "Pieve di Cadore",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Santa Maria Gloriosa dei Frari, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Titian",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paolo",
          lastName: "Caliari",
          knownAs: "Veronese",
          bornOn: 1528,
          diedOn: 1588,
          gender: "male",
          placeOfBirth: "Verona",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Chiesa di San Sebastiano, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Paolo_Veronese",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Albrecht",
          lastName: "Dürer",
          knownAs: null,
          bornOn: 1471,
          diedOn: 1528,
          gender: "male",
          placeOfBirth: "Nuremberg",
          placeOfDeath: "Nuremberg",
          nationality: "German",
          burialSite: "Johannisfriedhof Cemetery, Nuremberg",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Albrecht_D%C3%BCrer",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jheronimus",
          lastName: "van Aken",
          knownAs: "Hieronymus Bosch",
          bornOn: 1450,
          diedOn: 1516,
          gender: "male",
          placeOfBirth: "'s-Hertogenbosch",
          placeOfDeath: "'s-Hertogenbosch",
          nationality: "Dutch",
          burialSite: "St. John's Cathedral, 's-Hertogenbosch",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Hieronymus_Bosch",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Benvenuto",
          lastName: "Cellini",
          knownAs: null,
          bornOn: 1500,
          diedOn: 1571,
          gender: "male",
          placeOfBirth: "Florence",
          placeOfDeath: "Florence",
          nationality: "Italian",
          burialSite: "Santissima Annunziata, Florence",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Benvenuto_Cellini",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Girolamo Francesco",
          lastName: "Maria Mazzola",
          knownAs: "Parmigianino",
          bornOn: 1503,
          diedOn: 1540,
          gender: "male",
          placeOfBirth: "Parma",
          placeOfDeath: "Casalmaggiore",
          nationality: "Italian",
          burialSite: "Church of the Servite Friars, Florence",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Parmigianino",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jacopo",
          lastName: "Robusti",
          knownAs: "Tintoretto",
          bornOn: 1518,
          diedOn: 1594,
          gender: "male",
          placeOfBirth: "Venice",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Madonna dell'Orto, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Tintoretto",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Doménikos",
          lastName: "Theotokópoulos",
          knownAs: "El Greco",
          bornOn: 1541,
          diedOn: 1614,
          gender: "male",
          placeOfBirth: "Heraklion",
          placeOfDeath: "Toledo",
          nationality: "Greek",
          burialSite: "Monastery of Saint Dominic of Silos, Toledo",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/El_Greco",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hans",
          lastName: " Holbein",
          knownAs: "Hans Holbein the Younger",
          bornOn: 1497,
          diedOn: 1543,
          gender: "male",
          placeOfBirth: "Augsburg",
          placeOfDeath: "London",
          nationality: "German",
          burialSite: "St Katherine Cree Churchyard, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Hans_Holbein_the_Younger",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Pieter",
          lastName: "Bruegel",
          knownAs: "Pieter Bruegel the Elder",
          bornOn: 1530,
          diedOn: 1569,
          gender: "male",
          placeOfBirth: "Breda",
          placeOfDeath: "Brussels",
          nationality: "Flemish",
          burialSite: "Church of Notre Dame de la Chapelle, Brussels",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Pieter_Bruegel_the_Elder",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Michelangelo",
          lastName: "Merisi da Caravaggio",
          knownAs: "Caravaggio",
          bornOn: 1571,
          diedOn: 1610,
          gender: "male",
          placeOfBirth: "Milan",
          placeOfDeath: "Porto Ercole",
          nationality: "Italian",
          burialSite: "San Sebastiano cemetery, Porto Ercole",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Caravaggio",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Artemisia",
          lastName: "Gentileschi",
          knownAs: null,
          bornOn: 1593,
          diedOn: 1656,
          gender: "female",
          placeOfBirth: "Rome",
          placeOfDeath: "Naples",
          nationality: "Italian",
          burialSite:
            "Church of St. John of the Florentines (grave destroyed), Naples",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Artemisia_Gentileschi",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Francisco",
          lastName: "de Zurbarán",
          knownAs: null,
          bornOn: 1598,
          diedOn: 1664,
          gender: "male",
          placeOfBirth: "Fuente de Cantos",
          placeOfDeath: "Madrid",
          nationality: "Spanish",
          burialSite: null,
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Francisco_de_Zurbar%C3%A1n",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jusepe",
          lastName: "de Ribera",
          knownAs: null,
          bornOn: 1591,
          diedOn: 1652,
          gender: "male",
          placeOfBirth: "Xàtiva",
          placeOfDeath: "Naples",
          nationality: "Spanish",
          burialSite: "Church of Santa Maria del Parto in Mergellina, Naples",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jusepe_de_Ribera",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Bartolomé Esteban",
          lastName: "Murillo",
          knownAs: null,
          bornOn: 1618,
          diedOn: 1682,
          gender: "male",
          placeOfBirth: "Sevilla",
          placeOfDeath: "Sevilla",
          nationality: "Spanish",
          burialSite: null,
          painter: true,
          sculptor: false,
          wikiUrl:
            "https://en.wikipedia.org/wiki/Bartolom%C3%A9_Esteban_Murillo",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Guido",
          lastName: "Reni",
          knownAs: null,
          bornOn: 1575,
          diedOn: 1642,
          gender: "male",
          placeOfBirth: "Bologna",
          placeOfDeath: "Bologna",
          nationality: "Italian",
          burialSite: "Basilica of San Domenico, Bologna",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Guido_Reni",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Nicolas",
          lastName: "Poussin",
          knownAs: null,
          bornOn: 1594,
          diedOn: 1665,
          gender: "male",
          placeOfBirth: "Les Andelys",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "San Lorenzo in Lucina, Rome",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Nicolas_Poussin",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Claude",
          lastName: "Lorrain",
          knownAs: null,
          bornOn: 1600,
          diedOn: 1682,
          gender: "male",
          placeOfBirth: "Chamagne",
          placeOfDeath: "Rome",
          nationality: "French",
          burialSite: "San Luigi dei Francesi, Rome",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Claude_Lorrain",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Peter Paul",
          lastName: "Rubens",
          knownAs: null,
          bornOn: 1577,
          diedOn: 1640,
          gender: "male",
          placeOfBirth: "Siegen",
          placeOfDeath: "Antwerp",
          nationality: "Flemish",
          burialSite: "St. James' Church, Antwerp",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Peter_Paul_Rubens",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Anthony",
          lastName: "van Dyck",
          knownAs: null,
          bornOn: 1599,
          diedOn: 1641,
          gender: "male",
          placeOfBirth: "Antwerp",
          placeOfDeath: "London",
          nationality: "Flemish",
          burialSite: "St. Paul's Cathedral, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Anthony_van_Dyck",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Diego",
          lastName: "Rodríguez de Silva y Velázquez",
          knownAs: "Diego Velázquez",
          bornOn: 1599,
          diedOn: 1660,
          gender: "male",
          placeOfBirth: "Seville",
          placeOfDeath: "Madrid",
          nationality: "Spanish",
          burialSite: "Church of San Juan Bautista (destroyed), Madrid",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Diego_Vel%C3%A1zquez",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Frans",
          lastName: "Hals",
          knownAs: null,
          bornOn: 1582,
          diedOn: 1666,
          gender: "male",
          placeOfBirth: "Antwerp",
          placeOfDeath: "Haarlem",
          nationality: "Dutch",
          burialSite: "St. Bavo Church, Haarlem",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Frans_Hals",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Rembrandt",
          lastName: "van Rijn",
          knownAs: null,
          bornOn: 1606,
          diedOn: 1669,
          gender: "male",
          placeOfBirth: "Leiden",
          placeOfDeath: "Amsterdam",
          nationality: "Dutch",
          burialSite: "Westerkerk, Amsterdam",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Rembrandt",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Johannes",
          lastName: "Vermeer",
          knownAs: null,
          bornOn: 1632,
          diedOn: 1675,
          gender: "male",
          placeOfBirth: "Delft",
          placeOfDeath: "Delft",
          nationality: "Dutch",
          burialSite: "Oude Kerk, Delft",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Johannes_Vermeer",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Giovanni Antonio",
          lastName: "Canal",
          knownAs: "Canaletto",
          bornOn: 1697,
          diedOn: 1768,
          gender: "male",
          placeOfBirth: "Venice",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Church of San Lio, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Canaletto",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "William",
          lastName: "Hogarth",
          knownAs: null,
          bornOn: 1697,
          diedOn: 1764,
          gender: "male",
          placeOfBirth: "London",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St. Nicholas's Churchyard, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/William_Hogarth",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joshua",
          lastName: "Reynolds",
          knownAs: null,
          bornOn: 1723,
          diedOn: 1792,
          gender: "male",
          placeOfBirth: "Plympton",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St. Paul's Cathedral, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Joshua_Reynolds",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Thomas",
          lastName: "Gainsborough",
          knownAs: null,
          bornOn: 1727,
          diedOn: 1788,
          gender: "male",
          placeOfBirth: "Sudbury",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St Anne's Church, Kew, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Thomas_Gainsborough",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Antonio",
          lastName: "Canova",
          knownAs: null,
          bornOn: 1757,
          diedOn: 1822,
          gender: "male",
          placeOfBirth: "Possagno",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Santa Maria Gloriosa dei Frari, Venice",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Antonio_Canova",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Honoré",
          lastName: "Fragonard",
          knownAs: null,
          bornOn: 1732,
          diedOn: 1806,
          gender: "male",
          placeOfBirth: "Grasse",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Eglise Saint Roch, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean-Honor%C3%A9_Fragonard",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Maria Anna Angelika Kauffmann",
          lastName: "Kauffmann",
          knownAs: null,
          bornOn: 1741,
          diedOn: 1807,
          gender: "female",
          placeOfBirth: "Graubünden",
          placeOfDeath: "Rome",
          nationality: "Swiss",
          burialSite: "Sant'Andrea delle Fratte, Rome",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Angelica_Kauffman",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jacques-Louis",
          lastName: "David",
          knownAs: null,
          bornOn: 1748,
          diedOn: 1825,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Brussels",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jacques-Louis_David",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Francisco José",
          lastName: "de Goya y Lucientes",
          knownAs: "Francisco Goya",
          bornOn: 1746,
          diedOn: 1828,
          gender: "male",
          placeOfBirth: "Fuendetodos",
          placeOfDeath: "Bordeaux",
          nationality: "Spanish",
          burialSite: "Ermita de San Antonio de la Florida, Madrid",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Francisco_Goya",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "William",
          lastName: "Blake",
          knownAs: null,
          bornOn: 1757,
          diedOn: 1827,
          gender: "male",
          placeOfBirth: "London",
          placeOfDeath: "London",
          nationality: "",
          burialSite: "Bunhill Fields Burial Ground, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/William_Blake",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joseph Mallord William",
          lastName: "Turner",
          knownAs: "Willam Turner",
          bornOn: 1775,
          diedOn: 1851,
          gender: "male",
          placeOfBirth: "London",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St. Paul's Cathedral, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/J._M._W._Turner",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "John",
          lastName: "Constable",
          knownAs: null,
          bornOn: 1776,
          diedOn: 1837,
          gender: "male",
          placeOfBirth: "Suffolk",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St John-at-Hampstead, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/John_Constable",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Caspar David",
          lastName: "Friedrich",
          knownAs: null,
          bornOn: 1774,
          diedOn: 1840,
          gender: "male",
          placeOfBirth: "Greifswald",
          placeOfDeath: "Dresden",
          nationality: "German",
          burialSite: "Trinitatisfriedhof, Dresden",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Caspar_David_Friedrich",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Auguste-Dominique",
          lastName: "Ingres",
          knownAs: null,
          bornOn: 1780,
          diedOn: 1867,
          gender: "male",
          placeOfBirth: "Montauban",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl:
            "https://en.wikipedia.org/wiki/Jean-Auguste-Dominique_Ingres",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Katsushika",
          lastName: "Hokusai",
          knownAs: null,
          bornOn: 1760,
          diedOn: 1849,
          gender: "male",
          placeOfBirth: "Tokyo",
          placeOfDeath: "Tokyo",
          nationality: "Japanese",
          burialSite: "Seikyo-ji Temple Taitō-ku, Tokyo",
          painter: true,
          sculptor: false,
          wikiUrl: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Louis André Théodore",
          lastName: "Géricault",
          knownAs: "Théodore Géricaultl",
          bornOn: 1791,
          diedOn: 1824,
          gender: "male",
          placeOfBirth: "Rouen",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Th%C3%A9odore_G%C3%A9ricault",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ferdinand Victor Eugène",
          lastName: "Delacroix",
          knownAs: null,
          bornOn: 1798,
          diedOn: 1863,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Eug%C3%A8ne_Delacroix",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Honoré-Victorin",
          lastName: "Daumier",
          knownAs: "Honoré Daumier",
          bornOn: 1808,
          diedOn: 1879,
          gender: "male",
          placeOfBirth: "Marseille",
          placeOfDeath: "Valmondois",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Honor%C3%A9_Daumier",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Baptiste-Camille",
          lastName: "Corot",
          knownAs: null,
          bornOn: 1796,
          diedOn: 1875,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean-Baptiste-Camille_Corot",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-François",
          lastName: "Millet",
          knownAs: null,
          bornOn: 1814,
          diedOn: 1875,
          gender: "male",
          placeOfBirth: "Gruchy",
          placeOfDeath: "Barbizon",
          nationality: "French",
          burialSite: "Cimetière de Chailly-en-Bière, Chailly-en-Biere",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean-Fran%C3%A7ois_Millet",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean Désiré Gustave Courbet",
          lastName: "Courbet",
          knownAs: "Gustave Courbet",
          bornOn: 1819,
          diedOn: 1877,
          gender: "male",
          placeOfBirth: "Ornans",
          placeOfDeath: "La Tour-de-Peilz",
          nationality: "French",
          burialSite: "Ornans cemetery, Ornans",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Gustave_Courbet",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Rosa",
          lastName: "Bonheur",
          knownAs: null,
          bornOn: 1822,
          diedOn: 1899,
          gender: "female",
          placeOfBirth: "Bordeaux",
          placeOfDeath: "Thomery",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Rosa_Bonheur",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "William-Adolphe",
          lastName: "Bouguereau",
          knownAs: null,
          bornOn: 1825,
          diedOn: 1905,
          gender: "male",
          placeOfBirth: "La Rochelle",
          placeOfDeath: "La Rochelle",
          nationality: "French",
          burialSite: "Montparnasse Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/William-Adolphe_Bouguereau",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paul Gustave Louis Christophe",
          lastName: "Doré",
          knownAs: "Gustave Doré",
          bornOn: 1832,
          diedOn: 1883,
          gender: "male",
          placeOfBirth: "Strasbourg",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Gustave_Dor%C3%A9",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ignace Henri Jean Théodore",
          lastName: "Fantin-Latour",
          knownAs: "Henri Fantin-Latour",
          bornOn: 1836,
          diedOn: 1904,
          gender: "male",
          placeOfBirth: "Grenoble",
          placeOfDeath: "Buré",
          nationality: "French",
          burialSite: "Cimetière du Montparnasse, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Henri_Fantin-Latour",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Léon",
          lastName: "Gérôme",
          knownAs: null,
          bornOn: 1824,
          diedOn: 1904,
          gender: "male",
          placeOfBirth: "Vesoul",
          placeOfDeath: "Paris",
          nationality: "Montmartre Cemetery, Paris",
          burialSite: "French",
          painter: true,
          sculptor: true,
          wikiUrl:
            "https://en.wikipedia.org/wiki/Jean-L%C3%A9on_G%C3%A9r%C3%B4me",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Gabriel Charles Dante",
          lastName: "Rossetti",
          knownAs: "Dante Gabriel Rossetti",
          bornOn: 1828,
          diedOn: 1882,
          gender: "male",
          placeOfBirth: "London",
          placeOfDeath: "Kent",
          nationality: "English",
          burialSite: "All Saints Church, Birchington",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Dante_Gabriel_Rossetti",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "John Everett",
          lastName: "Millais",
          knownAs: null,
          bornOn: 1829,
          diedOn: 1896,
          gender: "male",
          placeOfBirth: "Southampton",
          placeOfDeath: "London,",
          nationality: "English",
          burialSite: "St. Paul's Cathedral, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/John_Everett_Millais",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Bertrand",
          lastName: "Redon",
          knownAs: "Odilon Redon",
          bornOn: 1840,
          diedOn: 1916,
          gender: "male",
          placeOfBirth: "Bordeaux",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Bievres Communal Churchyard, Bievres",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Odilon_Redon",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Gustav",
          lastName: "Klimt",
          knownAs: null,
          bornOn: 1862,
          diedOn: 1918,
          gender: "male",
          placeOfBirth: "Baumgarten",
          placeOfDeath: "Vienna",
          nationality: "Austrian",
          burialSite: "Hietzing Cemetery, Vienna",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Gustav_Klimt",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Egon",
          lastName: "Schiele",
          knownAs: null,
          bornOn: 1890,
          diedOn: 1918,
          gender: "male",
          placeOfBirth: "Tulln an der Donau",
          placeOfDeath: "Vienna",
          nationality: "Austrian",
          burialSite: "Cemetery Ober-Sankt-Veit, Vienna",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Egon_Schiele",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Édouard",
          lastName: "Manet",
          knownAs: null,
          bornOn: 1832,
          diedOn: 1883,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Passy Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/%C3%89douard_Manet",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Oscar-Claude",
          lastName: "Monet",
          knownAs: "Claude Monet",
          bornOn: 1840,
          diedOn: 1926,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Giverny",
          nationality: "French",
          burialSite: "Giverny Church Cemetery, Giverny",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Claude_Monet",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Pierre-Auguste",
          lastName: "Renoir",
          knownAs: null,
          bornOn: 1841,
          diedOn: 1919,
          gender: "male",
          placeOfBirth: "Limoges",
          placeOfDeath: "Cagnes-sur-Mer",
          nationality: "French",
          burialSite: "Essoyes Cimetière, Essoyes,",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Pierre-Auguste_Renoir",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hilaire-Germain-Edgar",
          lastName: "De Gas",
          knownAs: "Edgar Degas",
          bornOn: 1834,
          diedOn: 1917,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Montmartre Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Edgar_Degas",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "François Auguste René",
          lastName: "Rodin",
          knownAs: "Auguste Rodin",
          bornOn: 1840,
          diedOn: 1917,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Meudon",
          nationality: "French",
          burialSite: "Musée Rodin, Meudon",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Auguste_Rodin",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "James Abbott",
          lastName: "McNeill Whistler",
          knownAs: null,
          bornOn: 1834,
          diedOn: 1903,
          gender: "male",
          placeOfBirth: "Lowell, MA",
          placeOfDeath: "London",
          nationality: "American",
          burialSite: "Old Chiswick Cemetery, London",
          painter: true,
          sculptor: false,
          wikiUrl:
            "https://en.wikipedia.org/wiki/James_Abbott_McNeill_Whistler",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paul",
          lastName: "Cézanne",
          knownAs: null,
          bornOn: 1839,
          diedOn: 1906,
          gender: "male",
          placeOfBirth: "Aix-en-Provence",
          placeOfDeath: "Aix-en-Provence",
          nationality: "French",
          burialSite: "Saint-Pierre Cemetery, Aix-en-Provence",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Paul_C%C3%A9zanne",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Georges-Pierre",
          lastName: "Seurat",
          knownAs: "Georges Seurat",
          bornOn: 1859,
          diedOn: 1891,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Georges_Seurat",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Vincent Willem",
          lastName: "van Gogh",
          knownAs: "Vincent van Gogh",
          bornOn: 1853,
          diedOn: 1890,
          gender: "male",
          placeOfBirth: "Zundert",
          placeOfDeath: "Auvers-sur-Oise",
          nationality: "Dutch",
          burialSite: "Auvers-sur-Oise Town Cemetery, Auvers-sur-Oise",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Vincent_van_Gogh",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Eugène Henri Paul",
          lastName: "Gauguin",
          knownAs: "Paul Gauguin",
          bornOn: 1848,
          diedOn: 1903,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Atuona, Marquesas Islands",
          nationality: "French",
          burialSite: "Calvary Cemetery, Hiva-Oa",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Paul_Gauguin",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Edvard",
          lastName: "Munch",
          knownAs: null,
          bornOn: 1,
          diedOn: 1,
          gender: "male",
          placeOfBirth: "Ådalsbruk",
          placeOfDeath: "Oslo",
          nationality: "Norwegian",
          burialSite: "Our Savior's Cemetery, Oslo",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Edvard_Munch",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Käthe",
          lastName: "Kollwitz",
          knownAs: null,
          bornOn: 1867,
          diedOn: 1945,
          gender: "male",
          placeOfBirth: "Kaliningrad",
          placeOfDeath: "Moritzburg",
          nationality: "German",
          burialSite: "Zentralfriedhof, Friedrichsfelde",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/K%C3%A4the_Kollwitz",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Wassily",
          lastName: "Wassilyevich Kandinsky",
          knownAs: null,
          bornOn: 1866,
          diedOn: 1944,
          gender: "male",
          placeOfBirth: "Moscow",
          placeOfDeath: "Neuilly-sur-Seine",
          nationality: "Russian",
          burialSite: "Neuilly-sur-Seine community cemetery, Neuilly-sur-Seine",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Wassily_Kandinsky",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Henri Julien Félix",
          lastName: "Rousseau",
          knownAs: "Henri Rousseau",
          bornOn: 1844,
          diedOn: 1910,
          gender: "male",
          placeOfBirth: "Laval",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Cimetière de Bagneux, Bagneux",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Henri_Rousseau",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Henri Émile Benoît",
          lastName: "Matisse",
          knownAs: "Henri Matisse",
          bornOn: 1869,
          diedOn: 1954,
          gender: "male",
          placeOfBirth: "Le Cateau-Cambrésis",
          placeOfDeath: "Nice",
          nationality: "French",
          burialSite: "Cimiez Cemetery and Monastery, Cimiez",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Henri_Matisse",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "James Sidney Edouard",
          lastName: "Ensor",
          knownAs: "James Ensor",
          bornOn: 1860,
          diedOn: 1949,
          gender: "male",
          placeOfBirth: "Ostend",
          placeOfDeath: "Ostend",
          nationality: "Belgian",
          burialSite: "Onze-Lieve-Vrouw-ter-Duinenkerk, Ostend",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/James_Ensor",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Pablo Diego José Francisco",
          lastName:
            "de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Ruiz y Picasso",
          knownAs: "Pablo Picasso",
          bornOn: 1881,
          diedOn: 1973,
          gender: "male",
          placeOfBirth: "Malaga",
          placeOfDeath: "Mougins",
          nationality: "Spanish",
          burialSite: "Château of Vauvenargues, Vauvenargues",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Ch%C3%A2teau_of_Vauvenargues",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Georges",
          lastName: "Braque",
          knownAs: null,
          bornOn: 1882,
          diedOn: 1963,
          gender: "male",
          placeOfBirth: "Argenteuil",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite:
            "Cimetière marin de Varengeville-sur-Mer, Varengeville-sur-Mer",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Georges_Braque",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Umberto",
          lastName: "Boccioni",
          knownAs: null,
          bornOn: 1882,
          diedOn: 1916,
          gender: "male",
          placeOfBirth: "Reggio Calabria",
          placeOfDeath: "Verona",
          nationality: "Italian",
          burialSite: "Cimitero Monumentale, Verona",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Umberto_Boccioni",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "František",
          lastName: "Kupka",
          knownAs: null,
          bornOn: 1871,
          diedOn: 1957,
          gender: "male",
          placeOfBirth: "Opočno",
          placeOfDeath: "Puteaux",
          nationality: "Czech",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Franti%C5%A1ek_Kupka",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Robert",
          lastName: "Delaunay",
          knownAs: null,
          bornOn: 1885,
          diedOn: 1941,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Montpellier",
          nationality: "French",
          burialSite: "Cimetière de Gambais, Gambais",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Robert_Delaunay",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Kazimir",
          lastName: "Severinovich Malevich",
          knownAs: "Kazimir Malevich",
          bornOn: 1879,
          diedOn: 1935,
          gender: "male",
          placeOfBirth: "Kiev",
          placeOfDeath: "Leningrad",
          nationality: "Russian",
          burialSite: "Nemchinovka, Moscow",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Kazimir_Malevich",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paul",
          lastName: "Klee",
          knownAs: null,
          bornOn: 1879,
          diedOn: 1940,
          gender: "male",
          placeOfBirth: "Münchenbuchsee",
          placeOfDeath: "",
          nationality: "Swiss",
          burialSite: "Muralto",
          painter: true,
          sculptor: false,
          wikiUrl: "Schosshalden cemetery, Bern",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ernst Ludwig",
          lastName: "Kirchner",
          knownAs: null,
          bornOn: 1880,
          diedOn: 1938,
          gender: "male",
          placeOfBirth: "Aschaffenburg",
          placeOfDeath: "Frauenkirch-Wildboden",
          nationality: "German",
          burialSite: "Munich Waldfriedhof, Munich",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Ernst_Ludwig_Kirchner",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Henri-Robert-Marcel",
          lastName: "Duchamp",
          knownAs: "Marcel Duchamp",
          bornOn: 1887,
          diedOn: 1968,
          gender: "male",
          placeOfBirth: "Blainville-Crevon",
          placeOfDeath: "Neuilly-sur-Seine",
          nationality: "French",
          burialSite: "Rouen Cemetery, Rouen",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Marcel_Duchamp",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Constantin",
          lastName: "Brâncuși",
          knownAs: null,
          bornOn: 1867,
          diedOn: 1957,
          gender: "male",
          placeOfBirth: "Hobița",
          placeOfDeath: "Paris",
          nationality: "Romanian",
          burialSite: "Montparnasse Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl:
            "https://en.wikipedia.org/wiki/Constantin_Br%C3%A2ncu%C8%99i",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Pieter Cornelis",
          lastName: "Mondriaan",
          knownAs: "Piet Mondrian",
          bornOn: 1872,
          diedOn: 1944,
          gender: "male",
          placeOfBirth: "Amersfoort",
          placeOfDeath: "New York",
          nationality: "Dutch",
          burialSite: "Cypress Hills Cemetery, New York",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Piet_Mondrian",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Francis-Marie",
          lastName: "Martinez de Picabia",
          knownAs: "Francis Picabia",
          bornOn: 1879,
          diedOn: 1953,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Montmartre Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Francis_Picabia",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Max",
          lastName: "Ernst",
          knownAs: null,
          bornOn: 1891,
          diedOn: 1976,
          gender: "male",
          placeOfBirth: "Brühl",
          placeOfDeath: "Paris",
          nationality: "German",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Max_Ernst",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hans Peter Wilhelm",
          lastName: "Arp",
          knownAs: "Jean Arp",
          bornOn: 1886,
          diedOn: 1966,
          gender: "male",
          placeOfBirth: "Strasbourg",
          placeOfDeath: "Basel",
          nationality: "German-French",
          burialSite: "Cimitero di Locarno, Locarno",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean_Arp",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joan",
          lastName: "Miró i Ferrà",
          knownAs: "Joan Miró",
          bornOn: 1893,
          diedOn: 1983,
          gender: "male",
          placeOfBirth: "Barcelona",
          placeOfDeath: "Palma de Mallorca",
          nationality: "Spanish",
          burialSite: "Montjuïc Cemetery, Barcelona",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Joan_Mir%C3%B3",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Alexander",
          lastName: "Calder",
          knownAs: null,
          bornOn: 1898,
          diedOn: 1976,
          gender: "male",
          placeOfBirth: "Lawnton, PA",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Unknown",
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Alexander_Calder",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Dame Jocelyn Barbara",
          lastName: "Hepworth",
          knownAs: "Barbara Hepworth",
          bornOn: 1903,
          diedOn: 1975,
          gender: "male",
          placeOfBirth: "Wakefield",
          placeOfDeath: "St Ives",
          nationality: "English",
          burialSite: "Longstone Cemetery, Carbis Bay",
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Barbara_Hepworth",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Moïche Zakharovitch",
          lastName: "Chagalov",
          knownAs: "Marc Chagall",
          bornOn: 1887,
          diedOn: 1985,
          gender: "male",
          placeOfBirth: "Liozna",
          placeOfDeath: "Saint-Paul-de-Vence",
          nationality: "Russian",
          burialSite: "Saint Paul de Vence Cemetery, Saint Paul de Vence",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Marc_Chagall",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Edward",
          lastName: "Hopper",
          knownAs: null,
          bornOn: 1882,
          diedOn: 1967,
          gender: "male",
          placeOfBirth: "Nyack, NY",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Oak Hill Cemetery, Nyack, NY",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Edward_Hopper",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Grant",
          lastName: "DeVolson Wood",
          knownAs: "Grant Wood",
          bornOn: 1891,
          diedOn: 1942,
          gender: "male",
          placeOfBirth: "Anamosa, IA",
          placeOfDeath: "Iowa City, IA",
          nationality: "American",
          burialSite: "Riverside Cemetery, Anamosa, IA",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Grant_Wood",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Giorgio",
          lastName: "de Chirico",
          knownAs: null,
          bornOn: 1888,
          diedOn: 1978,
          gender: "male",
          placeOfBirth: "Volos",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "Chiesa di San Francesco a Ripa Grande, Rome",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Giorgio_de_Chirico",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "René François",
          lastName: "Ghislain Magritte",
          knownAs: "René Magritte",
          bornOn: 1898,
          diedOn: 1967,
          gender: "male",
          placeOfBirth: "Lessines",
          placeOfDeath: "Brussels",
          nationality: "Belgian",
          burialSite: "Communal cemetery Schaerbeek, Evere",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Ren%C3%A9_Magritte",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Salvador Domingo Felipe Jacinto",
          lastName: "Dalí i Domènech",
          knownAs: "Salvador Dalí",
          bornOn: 1904,
          diedOn: 1989,
          gender: "male",
          placeOfBirth: "Figueres",
          placeOfDeath: "Figueres",
          nationality: "Spanish",
          burialSite: "Dalí Theatre and Museum, Figueres",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Salvador_Dal%C3%AD",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          firstName: "Dorothea Margaret",
          lastName: "Tanning",
          knownAs: "Dorothea Tanning",
          bornOn: 1910,
          diedOn: 2012,
          gender: "female",
          placeOfBirth: "Galesburg, IL",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Dorothea_Tanning",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Diego María de la Concepción Juan Nepomuceno Estanislao",
          lastName: "de la Rivera y Barrientos Acosta y Rodríguez",
          knownAs: "Diego Rivera",
          bornOn: 1886,
          diedOn: 1957,
          gender: "male",
          placeOfBirth: "Guanajuato City",
          placeOfDeath: "Mexico City",
          nationality: "Mexican",
          burialSite: "Panteón de Dolores, Mexico City",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Diego_Rivera",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Magdalena Carmen Frida",
          lastName: "Kahlo y Calderón",
          knownAs: "Frida Kahlo",
          bornOn: 1907,
          diedOn: 1954,
          gender: "female",
          placeOfBirth: "Mexico City",
          placeOfDeath: "Mexico City",
          nationality: "Mexican",
          burialSite:
            "Londres St. in Coayocan (urn at her home address), Mexico",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Frida_Kahlo",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Georgia",
          lastName: "Totto O'Keeffe",
          knownAs: "Georgia O'Keeffe",
          bornOn: 1887,
          diedOn: 1986,
          gender: "female",
          placeOfBirth: "Sun Prairie, WI",
          placeOfDeath: "Santa Fe, NM",
          nationality: "American",
          burialSite: "Ashes scattered at The Pedernal, New Mexico",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Georgia_O%27Keeffe",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Markus",
          lastName: "Yakovlevich Rothkowitz",
          knownAs: "Mark Rothko",
          bornOn: 1903,
          diedOn: 1970,
          gender: "male",
          placeOfBirth: "Daugavpils",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "East Marion Cemetery, East Marion, NY",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Mark_Rothko",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paul",
          lastName: "Jackson Pollock",
          knownAs: "Jackson Pollock",
          bornOn: 1912,
          diedOn: 1956,
          gender: "male",
          placeOfBirth: "Cody, WY",
          placeOfDeath: "Springs, NY",
          nationality: "American",
          burialSite: "Green River Cemetery, Springs, NY",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jackson_Pollock",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Willem",
          lastName: "de Kooning",
          knownAs: null,
          bornOn: 1904,
          diedOn: 1997,
          gender: "male",
          placeOfBirth: "Rotterdam",
          placeOfDeath: "East Hampton",
          nationality: "Dutch-American",
          burialSite: "Unknown",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Willem_de_Kooning",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Yves",
          lastName: "Klein",
          knownAs: null,
          bornOn: 1928,
          diedOn: 1962,
          gender: "male",
          placeOfBirth: "Nice",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "La Colle-sur-Loup Cemetery, La Colle-sur-Loup",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Yves_Klein",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joseph",
          lastName: "Beuys",
          knownAs: null,
          bornOn: 1921,
          diedOn: 1986,
          gender: "male",
          placeOfBirth: "Krefeld",
          placeOfDeath: "Düsseldorf",
          nationality: "German",
          burialSite: "Cremated, ashes scatterd at Nordsee",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Joseph_Beuys",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Francis",
          lastName: "Bacon",
          knownAs: null,
          bornOn: 1909,
          diedOn: 1992,
          gender: "male",
          placeOfBirth: "Dublin",
          placeOfDeath: "Madrid",
          nationality: "English",
          burialSite: "Cremated, Ashes given to family or friend",
          painter: true,
          sculptor: false,
          wikiUrl: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Andrew",
          lastName: "Warhola",
          knownAs: "Andy Warhol",
          bornOn: 1928,
          diedOn: 1987,
          gender: "male",
          placeOfBirth: "Pittsburgh, PA",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite:
            "St. John the Baptist Byzantine Catholic Cemetery, Bethel Park, PA",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Andy_Warhol",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Michel",
          lastName: "Basquiat",
          knownAs: null,
          bornOn: 1960,
          diedOn: 1988,
          gender: "male",
          placeOfBirth: "New York City, NY",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Green-Wood Cemetery, Brooklyn, NY",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean-Michel_Basquiat",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Roy Fox",
          lastName: "Lichtenstein[",
          knownAs: "Roy Lichtenstein",
          bornOn: 1923,
          diedOn: 1997,
          gender: "male",
          placeOfBirth: "New York City, NY",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Cremated, Ashes given to family or friend",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Roy_Lichtenstein",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Allan",
          lastName: "Kaprow",
          knownAs: null,
          bornOn: 1927,
          diedOn: 2006,
          gender: "male",
          placeOfBirth: "Atlantic City, NJ",
          placeOfDeath: "Encinitas, CA",
          nationality: "American",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Allan_Kaprow",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Christiaan Karel",
          lastName: "Appel",
          knownAs: "Karel Appel",
          bornOn: 1921,
          diedOn: 2006,
          gender: "male",
          placeOfBirth: "Amsterdam",
          placeOfDeath: "Zürich",
          nationality: "Dutch",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Karel_Appel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Nam June",
          lastName: "Paik",
          knownAs: null,
          bornOn: 1932,
          diedOn: 2006,
          gender: "male",
          placeOfBirth: "Seoul",
          placeOfDeath: "Miami, FL",
          nationality: "Korean-American",
          burialSite: "Cremated, ashes spread in many different locations",
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Nam_June_Paik",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Donald Clarence",
          lastName: "Judd",
          knownAs: "Donald Judd",
          bornOn: 1928,
          diedOn: 1994,
          gender: "male",
          placeOfBirth: "Excelsior Springs, MO",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Judd Ranch, Marfa, TX",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Donald_Judd",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Louise Joséphine",
          lastName: "Bourgeois",
          knownAs: "Louise Bourgeois",
          bornOn: 1911,
          diedOn: 2010,
          gender: "female",
          placeOfBirth: "Paris",
          placeOfDeath: "New York City, NY",
          nationality: "French-American",
          burialSite: "Cutchogue Cemetery, Cutchogue, NY",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Louise_Bourgeois",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Edwin Parker Cy",
          lastName: "Twombly",
          knownAs: "Cy Twombly",
          bornOn: 1928,
          diedOn: 2011,
          gender: "male",
          placeOfBirth: "Lexington, VI",
          placeOfDeath: "Rome",
          nationality: "American",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Cy_Twombly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Arnaldo",
          lastName: "Pomodoro",
          knownAs: null,
          bornOn: 1926,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Morciano",
          placeOfDeath: null,
          nationality: "Italian",
          burialSite: null,
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Arnaldo_Pomodoro",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Claes",
          lastName: "Oldenburg",
          knownAs: null,
          bornOn: 1929,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Stockholm",
          placeOfDeath: null,
          nationality: "Swedish-American",
          burialSite: null,
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Claes_Oldenburg",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          firstName: "Gerhard",
          lastName: "Richter",
          knownAs: null,
          bornOn: 1932,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Dresden",
          placeOfDeath: null,
          nationality: "German",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Gerhard_Richter",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Yoko",
          lastName: "Ono Lennon",
          knownAs: "Yoko Ono",
          bornOn: 1933,
          diedOn: null,
          gender: "female",
          placeOfBirth: "Tokyo",
          placeOfDeath: null,
          nationality: "Japanese",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Yoko_Ono",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Richard",
          lastName: "Serra",
          knownAs: null,
          bornOn: 1938,
          diedOn: null,
          gender: "male",
          placeOfBirth: "San Francisco, CA",
          placeOfDeath: null,
          nationality: "American",
          burialSite: null,
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Richard_Serra",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Barbara",
          lastName: "Kruger",
          knownAs: null,
          bornOn: 1945,
          diedOn: null,
          gender: "female",
          placeOfBirth: "Newark, NJ",
          placeOfDeath: null,
          nationality: "American",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Anselm",
          lastName: "Kiefer",
          knownAs: null,
          bornOn: 1945,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Donaueschingen",
          placeOfDeath: null,
          nationality: "German",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Anselm_Kiefer",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Marina",
          lastName: "Abramović",
          knownAs: null,
          bornOn: 1946,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Belgrade",
          placeOfDeath: null,
          nationality: "Serbian",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Bill",
          lastName: "Viola",
          knownAs: null,
          bornOn: 1951,
          diedOn: null,
          gender: "male",
          placeOfBirth: "New York City, NY",
          placeOfDeath: null,
          nationality: "American",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Bill_Viola",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jeffrey L.",
          lastName: "Koons",
          knownAs: "Jeff Koons",
          bornOn: 1955,
          diedOn: null,
          gender: "male",
          placeOfBirth: "York, PA",
          placeOfDeath: null,
          nationality: "American",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Jeff_Koons",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ai",
          lastName: "Weiwei",
          knownAs: null,
          bornOn: 1957,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Beijing",
          placeOfDeath: null,
          nationality: "Chinese",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Ai_Weiwei",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Maurizio",
          lastName: "Cattelan",
          knownAs: null,
          bornOn: 1960,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Padua",
          placeOfDeath: null,
          nationality: "Italian",
          burialSite: null,
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Maurizio_Cattelan",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Tracey",
          lastName: "Emin",
          knownAs: null,
          bornOn: 1963,
          diedOn: null,
          gender: "female",
          placeOfBirth: "Croydon",
          placeOfDeath: null,
          nationality: "English",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Tracey_Emin",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Damien",
          lastName: "Hirst",
          knownAs: null,
          bornOn: 1965,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Bristol",
          placeOfDeath: null,
          nationality: "",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: null,
          lastName: null,
          knownAs: "Banksy",
          bornOn: null,
          diedOn: null,
          gender: null,
          placeOfBirth: "Bristol",
          placeOfDeath: null,
          nationality: "English",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("artists", null, {});
  },
};
