"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "artists",
      [
        {
          firstName: "Tommaso",
          lastName: "di Ser Giovanni di Simone",
          knownAs: "Masaccio",
          bornOn: 1401,
          diedOn: 1428,
          gender: "male",
          placeOfBirth: "San Giovanni Valdarno",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "Chiesa di Santa Maria del Carmine, Florence",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Masaccio",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Donato",
          lastName: "di Niccolò di Betto Bardi",
          knownAs: "Donatello",
          bornOn: 1386,
          diedOn: 1466,
          gender: "male",
          placeOfBirth: "Florence",
          placeOfDeath: "Florence",
          nationality: "Italian",
          burialSite: "Basilica di San Lorenzo, Florence",
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Donatello",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jan",
          lastName: "van Eyck",
          knownAs: null,
          bornOn: 1395,
          diedOn: 1441,
          gender: "male",
          placeOfBirth: "Maaseik",
          placeOfDeath: "Bruges",
          nationality: "Flemish",
          burialSite: "St. Donatian's Cathedral, Bruges",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jan_van_Eyck",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Rogier",
          lastName: "van der Weyden",
          knownAs: null,
          bornOn: 1399,
          diedOn: 1464,
          gender: "male",
          placeOfBirth: "Tournai",
          placeOfDeath: "Brussels",
          nationality: "Flemish",
          burialSite: "St Michael and St Gudula Cathedral, Brussels",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Rogier_van_der_Weyden",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Dieric",
          lastName: "Bouts",
          knownAs: null,
          bornOn: 1415,
          diedOn: 1475,
          gender: "male",
          placeOfBirth: "Haarlem",
          placeOfDeath: "Leuven",
          nationality: "Flemish",
          burialSite: "Franciscan church of Leuven",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Dieric_Bouts",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Alessandro",
          lastName: "di Mariano di Vanni Filipepi",
          knownAs: "Sandro Botticelli",
          bornOn: 1445,
          diedOn: 1510,
          gender: "male",
          placeOfBirth: "Florence",
          placeOfDeath: "Florence",
          nationality: "Italian",
          burialSite: "Chiesa di San Salvatore in Ognissanti, Florence",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Sandro_Botticelli",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hugo",
          lastName: "van der Goes",
          knownAs: null,
          bornOn: 1430,
          diedOn: 1482,
          gender: "male",
          placeOfBirth: "Ghent",
          placeOfDeath: "Auderghem",
          nationality: "Flemish",
          burialSite: "Red Cloister, Brussels",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Hugo_van_der_Goes",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Leonardo",
          lastName: "di ser Piero da Vinci",
          knownAs: "Leonardo da Vinci",
          bornOn: 1452,
          diedOn: 1519,
          gender: "male",
          placeOfBirth: "Vinci",
          placeOfDeath: "Amboise",
          nationality: "Italian",
          burialSite: "Chapel of Saint-Hubert, Amboise",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Leonardo_da_Vinci",
          imageUrl:
            "https://images-na.ssl-images-amazon.com/images/I/71t8tOnINfL._AC_SY679_.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Michelangelo",
          lastName: "di Lodovico Buonarroti Simoni",
          knownAs: "Michelangelo",
          bornOn: 1475,
          diedOn: 1564,
          gender: "male",
          placeOfBirth: "Caprese",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "Basilica of Santa Croce, Florence",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Michelangelo",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Miguel_%C3%81ngel%2C_por_Daniele_da_Volterra_%28detalle%29.jpg/415px-Miguel_%C3%81ngel%2C_por_Daniele_da_Volterra_%28detalle%29.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Raffaello",
          lastName: "Sanzio da Urbino",
          knownAs: "Raphael",
          bornOn: 1483,
          diedOn: 1520,
          gender: "male",
          placeOfBirth: "Urbino",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "Pantheon, Rome",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Raphael",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Raffaello_Sanzio.jpg/352px-Raffaello_Sanzio.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Giovanni",
          lastName: "Bellini",
          knownAs: null,
          bornOn: 1430,
          diedOn: 1516,
          gender: "male",
          placeOfBirth: "Venice",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Basilica di San Giovanni e Paolo, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Giovanni_Bellini",
          imageUrl:
            "https://d32dm0rphc51dk.cloudfront.net/mOH2QwnxDu6LG_FJHPMIrQ/large.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Giorgio",
          lastName: "Barbarelli da Castelfranco",
          knownAs: "Giorgione",
          bornOn: 1477,
          diedOn: 1510,
          gender: "male",
          placeOfBirth: "Castelfranco Veneto",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Island of Poveglia(?), Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Giorgione",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Giorgione_059.jpg/594px-Giorgione_059.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Tiziano",
          lastName: "Vecelli",
          knownAs: "Titian",
          bornOn: 1488,
          diedOn: 1576,
          gender: "male",
          placeOfBirth: "Pieve di Cadore",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Santa Maria Gloriosa dei Frari, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Titian",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Self-portrait_of_Titian.jpg/361px-Self-portrait_of_Titian.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paolo",
          lastName: "Caliari",
          knownAs: "Veronese",
          bornOn: 1528,
          diedOn: 1588,
          gender: "male",
          placeOfBirth: "Verona",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Chiesa di San Sebastiano, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Paolo_Veronese",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Paolo_Veronese%2C_avtoportret.jpg/382px-Paolo_Veronese%2C_avtoportret.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Albrecht",
          lastName: "Dürer",
          knownAs: null,
          bornOn: 1471,
          diedOn: 1528,
          gender: "male",
          placeOfBirth: "Nuremberg",
          placeOfDeath: "Nuremberg",
          nationality: "German",
          burialSite: "Johannisfriedhof Cemetery, Nuremberg",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Albrecht_D%C3%BCrer",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/D%C3%BCrer_-_Selbstbildnis_im_Pelzrock_-_Alte_Pinakothek.jpg/341px-D%C3%BCrer_-_Selbstbildnis_im_Pelzrock_-_Alte_Pinakothek.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jheronimus",
          lastName: "van Aken",
          knownAs: "Hieronymus Bosch",
          bornOn: 1450,
          diedOn: 1516,
          gender: "male",
          placeOfBirth: "'s-Hertogenbosch",
          placeOfDeath: "'s-Hertogenbosch",
          nationality: "Dutch",
          burialSite: "St. John's Cathedral, 's-Hertogenbosch",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Hieronymus_Bosch",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Jheronimus_Bosch_%28cropped%29.jpg/412px-Jheronimus_Bosch_%28cropped%29.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Benvenuto",
          lastName: "Cellini",
          knownAs: null,
          bornOn: 1500,
          diedOn: 1571,
          gender: "male",
          placeOfBirth: "Florence",
          placeOfDeath: "Florence",
          nationality: "Italian",
          burialSite: "Santissima Annunziata, Florence",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Benvenuto_Cellini",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Portrait_of_a_bearded_man._Cellini%2C_Benvenuto.png/303px-Portrait_of_a_bearded_man._Cellini%2C_Benvenuto.png",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Girolamo Francesco",
          lastName: "Maria Mazzola",
          knownAs: "Parmigianino",
          bornOn: 1503,
          diedOn: 1540,
          gender: "male",
          placeOfBirth: "Parma",
          placeOfDeath: "Casalmaggiore",
          nationality: "Italian",
          burialSite: "Church of the Servite Friars, Florence",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Parmigianino",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Parmigianino_Selfportrait.jpg/481px-Parmigianino_Selfportrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jacopo",
          lastName: "Robusti",
          knownAs: "Tintoretto",
          bornOn: 1518,
          diedOn: 1594,
          gender: "male",
          placeOfBirth: "Venice",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Madonna dell'Orto, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Tintoretto",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Jacopo_Tintoretto_031-2.jpg/384px-Jacopo_Tintoretto_031-2.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Doménikos",
          lastName: "Theotokópoulos",
          knownAs: "El Greco",
          bornOn: 1541,
          diedOn: 1614,
          gender: "male",
          placeOfBirth: "Heraklion",
          placeOfDeath: "Toledo",
          nationality: "Greek",
          burialSite: "Monastery of Saint Dominic of Silos, Toledo",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/El_Greco",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/El_Greco_-_Portrait_of_a_Man_-_WGA10554.jpg/433px-El_Greco_-_Portrait_of_a_Man_-_WGA10554.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hans",
          lastName: "Holbein",
          knownAs: "Hans Holbein the Younger",
          bornOn: 1497,
          diedOn: 1543,
          gender: "male",
          placeOfBirth: "Augsburg",
          placeOfDeath: "London",
          nationality: "German",
          burialSite: "St Katherine Cree Churchyard, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Hans_Holbein_the_Younger",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Hans_Holbein_the_Younger%2C_self-portrait.jpg/351px-Hans_Holbein_the_Younger%2C_self-portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Pieter",
          lastName: "Bruegel",
          knownAs: "Pieter Bruegel the Elder",
          bornOn: 1530,
          diedOn: 1569,
          gender: "male",
          placeOfBirth: "Breda",
          placeOfDeath: "Brussels",
          nationality: "Flemish",
          burialSite: "Church of Notre Dame de la Chapelle, Brussels",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Pieter_Bruegel_the_Elder",
          imageUrl:
            "https://uploads7.wikiart.org/images/pieter-bruegel-the-elder.jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Michelangelo",
          lastName: "Merisi da Caravaggio",
          knownAs: "Caravaggio",
          bornOn: 1571,
          diedOn: 1610,
          gender: "male",
          placeOfBirth: "Milan",
          placeOfDeath: "Porto Ercole",
          nationality: "Italian",
          burialSite: "San Sebastiano cemetery, Porto Ercole",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Caravaggio",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Bild-Ottavio_Leoni%2C_Caravaggio.jpg/361px-Bild-Ottavio_Leoni%2C_Caravaggio.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Artemisia",
          lastName: "Gentileschi",
          knownAs: null,
          bornOn: 1593,
          diedOn: 1656,
          gender: "female",
          placeOfBirth: "Rome",
          placeOfDeath: "Naples",
          nationality: "Italian",
          burialSite:
            "Church of St. John of the Florentines (grave destroyed), Naples",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Artemisia_Gentileschi",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Self-portrait_as_the_Allegory_of_Painting_%28La_Pittura%29_-_Artemisia_Gentileschi.jpg/360px-Self-portrait_as_the_Allegory_of_Painting_%28La_Pittura%29_-_Artemisia_Gentileschi.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Francisco",
          lastName: "de Zurbarán",
          knownAs: null,
          bornOn: 1598,
          diedOn: 1664,
          gender: "male",
          placeOfBirth: "Fuente de Cantos",
          placeOfDeath: "Madrid",
          nationality: "Spanish",
          burialSite: null,
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Francisco_de_Zurbar%C3%A1n",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Francisco_de_Zurbar%C3%A1n_autoportrait.jpg/393px-Francisco_de_Zurbar%C3%A1n_autoportrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jusepe",
          lastName: "de Ribera",
          knownAs: null,
          bornOn: 1591,
          diedOn: 1652,
          gender: "male",
          placeOfBirth: "Xàtiva",
          placeOfDeath: "Naples",
          nationality: "Spanish",
          burialSite: "Church of Santa Maria del Parto in Mergellina, Naples",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jusepe_de_Ribera",
          imageUrl:
            "https://uploads8.wikiart.org/temp/52baa6e5-9938-4006-9ce9-306efc9c1ff8.jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Bartolomé Esteban",
          lastName: "Murillo",
          knownAs: null,
          bornOn: 1618,
          diedOn: 1682,
          gender: "male",
          placeOfBirth: "Sevilla",
          placeOfDeath: "Sevilla",
          nationality: "Spanish",
          burialSite: null,
          painter: true,
          sculptor: false,
          wikiUrl:
            "https://en.wikipedia.org/wiki/Bartolom%C3%A9_Esteban_Murillo",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Autorretrato_de_Murillo.jpg/434px-Autorretrato_de_Murillo.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Guido",
          lastName: "Reni",
          knownAs: null,
          bornOn: 1575,
          diedOn: 1642,
          gender: "male",
          placeOfBirth: "Bologna",
          placeOfDeath: "Bologna",
          nationality: "Italian",
          burialSite: "Basilica of San Domenico, Bologna",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Guido_Reni",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Guido_Reni_-_Self-portrait_2.jpg/389px-Guido_Reni_-_Self-portrait_2.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Nicolas",
          lastName: "Poussin",
          knownAs: null,
          bornOn: 1594,
          diedOn: 1665,
          gender: "male",
          placeOfBirth: "Les Andelys",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "San Lorenzo in Lucina, Rome",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Nicolas_Poussin",
          imageUrl: "http://cdn2.all-art.org/baroque/images/poussin/63.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Claude",
          lastName: "Lorrain",
          knownAs: null,
          bornOn: 1600,
          diedOn: 1682,
          gender: "male",
          placeOfBirth: "Chamagne",
          placeOfDeath: "Rome",
          nationality: "French",
          burialSite: "San Luigi dei Francesi, Rome",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Claude_Lorrain",
          imageUrl:
            "https://uploads6.wikiart.org/images/claude-lorrain.jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Peter Paul",
          lastName: "Rubens",
          knownAs: null,
          bornOn: 1577,
          diedOn: 1640,
          gender: "male",
          placeOfBirth: "Siegen",
          placeOfDeath: "Antwerp",
          nationality: "Flemish",
          burialSite: "St. James' Church, Antwerp",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Peter_Paul_Rubens",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Anthony",
          lastName: "van Dyck",
          knownAs: null,
          bornOn: 1599,
          diedOn: 1641,
          gender: "male",
          placeOfBirth: "Antwerp",
          placeOfDeath: "London",
          nationality: "Flemish",
          burialSite: "St. Paul's Cathedral, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Anthony_van_Dyck",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Diego",
          lastName: "Rodríguez de Silva y Velázquez",
          knownAs: "Diego Velázquez",
          bornOn: 1599,
          diedOn: 1660,
          gender: "male",
          placeOfBirth: "Seville",
          placeOfDeath: "Madrid",
          nationality: "Spanish",
          burialSite: "Church of San Juan Bautista (destroyed), Madrid",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Diego_Vel%C3%A1zquez",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Frans",
          lastName: "Hals",
          knownAs: null,
          bornOn: 1582,
          diedOn: 1666,
          gender: "male",
          placeOfBirth: "Antwerp",
          placeOfDeath: "Haarlem",
          nationality: "Dutch",
          burialSite: "St. Bavo Church, Haarlem",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Frans_Hals",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Hals_-_Self-Portrait_copy.jpg/413px-Hals_-_Self-Portrait_copy.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Rembrandt",
          lastName: "van Rijn",
          knownAs: null,
          bornOn: 1606,
          diedOn: 1669,
          gender: "male",
          placeOfBirth: "Leiden",
          placeOfDeath: "Amsterdam",
          nationality: "Dutch",
          burialSite: "Westerkerk, Amsterdam",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Rembrandt",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Rembrandt_Self-portrait_%28Kenwood%29.jpg/398px-Rembrandt_Self-portrait_%28Kenwood%29.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Johannes",
          lastName: "Vermeer",
          knownAs: null,
          bornOn: 1632,
          diedOn: 1675,
          gender: "male",
          placeOfBirth: "Delft",
          placeOfDeath: "Delft",
          nationality: "Dutch",
          burialSite: "Oude Kerk, Delft",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Johannes_Vermeer",
          imageUrl:
            "https://uploads8.wikiart.org/images/johannes-vermeer.jpg!Portrait.jpg",
          bio:
            "Johannes Vermeer was a Dutch artist who created paintings that are among the most beloved and revered images in the history of art. Although only about 36 of his paintings survive, these rare works are among the greatest treasures in the world’s finest museums. Vermeer began his career in the early 1650s by painting large-scale biblical and mythological scenes, but most of his later paintings—the ones for which he is most famous—depict scenes of daily life in interior settings. These works are remarkable for their purity of light and form, qualities that convey a serene, timeless sense of dignity. Vermeer also painted cityscapes and allegorical scenes.",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Giovanni Antonio",
          lastName: "Canal",
          knownAs: "Canaletto",
          bornOn: 1697,
          diedOn: 1768,
          gender: "male",
          placeOfBirth: "Venice",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Church of San Lio, Venice",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Canaletto",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "William",
          lastName: "Hogarth",
          knownAs: null,
          bornOn: 1697,
          diedOn: 1764,
          gender: "male",
          placeOfBirth: "London",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St. Nicholas's Churchyard, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/William_Hogarth",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joshua",
          lastName: "Reynolds",
          knownAs: null,
          bornOn: 1723,
          diedOn: 1792,
          gender: "male",
          placeOfBirth: "Plympton",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St. Paul's Cathedral, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Joshua_Reynolds",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Thomas",
          lastName: "Gainsborough",
          knownAs: null,
          bornOn: 1727,
          diedOn: 1788,
          gender: "male",
          placeOfBirth: "Sudbury",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St Anne's Church, Kew, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Thomas_Gainsborough",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Antonio",
          lastName: "Canova",
          knownAs: null,
          bornOn: 1757,
          diedOn: 1822,
          gender: "male",
          placeOfBirth: "Possagno",
          placeOfDeath: "Venice",
          nationality: "Italian",
          burialSite: "Santa Maria Gloriosa dei Frari, Venice",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Antonio_Canova",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Honoré",
          lastName: "Fragonard",
          knownAs: null,
          bornOn: 1732,
          diedOn: 1806,
          gender: "male",
          placeOfBirth: "Grasse",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Eglise Saint Roch, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean-Honor%C3%A9_Fragonard",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Maria Anna Angelika",
          lastName: "Kauffmann",
          knownAs: "Angelica Kauffman",
          bornOn: 1741,
          diedOn: 1807,
          gender: "female",
          placeOfBirth: "Graubünden",
          placeOfDeath: "Rome",
          nationality: "Swiss",
          burialSite: "Sant'Andrea delle Fratte, Rome",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Angelica_Kauffman",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Angelica_Kauffmann_by_Angelica_Kauffmann.jpg/398px-Angelica_Kauffmann_by_Angelica_Kauffmann.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jacques-Louis",
          lastName: "David",
          knownAs: null,
          bornOn: 1748,
          diedOn: 1825,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Brussels",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jacques-Louis_David",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Francisco José",
          lastName: "de Goya y Lucientes",
          knownAs: "Francisco Goya",
          bornOn: 1746,
          diedOn: 1828,
          gender: "male",
          placeOfBirth: "Fuendetodos",
          placeOfDeath: "Bordeaux",
          nationality: "Spanish",
          burialSite: "Ermita de San Antonio de la Florida, Madrid",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Francisco_Goya",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Autorretrato_Goya_1815.jpg/357px-Autorretrato_Goya_1815.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "William",
          lastName: "Blake",
          knownAs: null,
          bornOn: 1757,
          diedOn: 1827,
          gender: "male",
          placeOfBirth: "London",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "Bunhill Fields Burial Ground, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/William_Blake",
          imageUrl:
            "https://collectionimages.npg.org.uk/large/mw00609/William-Blake.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joseph Mallord William",
          lastName: "Turner",
          knownAs: "Willam Turner",
          bornOn: 1775,
          diedOn: 1851,
          gender: "male",
          placeOfBirth: "London",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St. Paul's Cathedral, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/J._M._W._Turner",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "John",
          lastName: "Constable",
          knownAs: null,
          bornOn: 1776,
          diedOn: 1837,
          gender: "male",
          placeOfBirth: "Suffolk",
          placeOfDeath: "London",
          nationality: "English",
          burialSite: "St John-at-Hampstead, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/John_Constable",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Caspar David",
          lastName: "Friedrich",
          knownAs: null,
          bornOn: 1774,
          diedOn: 1840,
          gender: "male",
          placeOfBirth: "Greifswald",
          placeOfDeath: "Dresden",
          nationality: "German",
          burialSite: "Trinitatisfriedhof, Dresden",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Caspar_David_Friedrich",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Auguste-Dominique",
          lastName: "Ingres",
          knownAs: null,
          bornOn: 1780,
          diedOn: 1867,
          gender: "male",
          placeOfBirth: "Montauban",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl:
            "https://en.wikipedia.org/wiki/Jean-Auguste-Dominique_Ingres",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Katsushika",
          lastName: "Hokusai",
          knownAs: null,
          bornOn: 1760,
          diedOn: 1849,
          gender: "male",
          placeOfBirth: "Tokyo",
          placeOfDeath: "Tokyo",
          nationality: "Japanese",
          burialSite: "Seikyo-ji Temple Taitō-ku, Tokyo",
          painter: true,
          sculptor: false,
          wikiUrl: "",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Louis André Théodore",
          lastName: "Géricault",
          knownAs: "Théodore Géricault",
          bornOn: 1791,
          diedOn: 1824,
          gender: "male",
          placeOfBirth: "Rouen",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Th%C3%A9odore_G%C3%A9ricault",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ferdinand Victor Eugène",
          lastName: "Delacroix",
          knownAs: null,
          bornOn: 1798,
          diedOn: 1863,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Eug%C3%A8ne_Delacroix",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/F%C3%A9lix_Nadar_1820-1910_portraits_Eug%C3%A8ne_Delacroix_restored.jpg/349px-F%C3%A9lix_Nadar_1820-1910_portraits_Eug%C3%A8ne_Delacroix_restored.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Honoré-Victorin",
          lastName: "Daumier",
          knownAs: "Honoré Daumier",
          bornOn: 1808,
          diedOn: 1879,
          gender: "male",
          placeOfBirth: "Marseille",
          placeOfDeath: "Valmondois",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Honor%C3%A9_Daumier",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Baptiste-Camille",
          lastName: "Corot",
          knownAs: null,
          bornOn: 1796,
          diedOn: 1875,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean-Baptiste-Camille_Corot",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-François",
          lastName: "Millet",
          knownAs: null,
          bornOn: 1814,
          diedOn: 1875,
          gender: "male",
          placeOfBirth: "Gruchy",
          placeOfDeath: "Barbizon",
          nationality: "French",
          burialSite: "Cimetière de Chailly-en-Bière, Chailly-en-Biere",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean-Fran%C3%A7ois_Millet",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean Désiré Gustave Courbet",
          lastName: "Courbet",
          knownAs: "Gustave Courbet",
          bornOn: 1819,
          diedOn: 1877,
          gender: "male",
          placeOfBirth: "Ornans",
          placeOfDeath: "La Tour-de-Peilz",
          nationality: "French",
          burialSite: "Ornans cemetery, Ornans",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Gustave_Courbet",
          imageUrl:
            "https://d7hftxdivxxvm.cloudfront.net/?resize_to=width&src=https%3A%2F%2Fartsy-media-uploads.s3.amazonaws.com%2Fw96OnhVmTGLkwF447ILLHg%252F1251px-Gustave_Courbet_-_Le_De%25CC%2581sespe%25CC%2581re%25CC%2581.JPG&width=600&quality=80",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Rosa",
          lastName: "Bonheur",
          knownAs: null,
          bornOn: 1822,
          diedOn: 1899,
          gender: "female",
          placeOfBirth: "Bordeaux",
          placeOfDeath: "Thomery",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Rosa_Bonheur",
          imageUrl:
            "https://uploads4.wikiart.org/images/rosa-bonheur.jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "William-Adolphe",
          lastName: "Bouguereau",
          knownAs: null,
          bornOn: 1825,
          diedOn: 1905,
          gender: "male",
          placeOfBirth: "La Rochelle",
          placeOfDeath: "La Rochelle",
          nationality: "French",
          burialSite: "Montparnasse Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/William-Adolphe_Bouguereau",
          imageUrl:
            "https://uploads0.wikiart.org/images/william-adolphe-bouguereau.jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paul Gustave Louis Christophe",
          lastName: "Doré",
          knownAs: "Gustave Doré",
          bornOn: 1832,
          diedOn: 1883,
          gender: "male",
          placeOfBirth: "Strasbourg",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Gustave_Dor%C3%A9",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ignace Henri Jean Théodore",
          lastName: "Fantin-Latour",
          knownAs: "Henri Fantin-Latour",
          bornOn: 1836,
          diedOn: 1904,
          gender: "male",
          placeOfBirth: "Grenoble",
          placeOfDeath: "Buré",
          nationality: "French",
          burialSite: "Cimetière du Montparnasse, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Henri_Fantin-Latour",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Léon",
          lastName: "Gérôme",
          knownAs: null,
          bornOn: 1824,
          diedOn: 1904,
          gender: "male",
          placeOfBirth: "Vesoul",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Montmartre Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl:
            "https://en.wikipedia.org/wiki/Jean-L%C3%A9on_G%C3%A9r%C3%B4me",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Gabriel Charles Dante",
          lastName: "Rossetti",
          knownAs: "Dante Gabriel Rossetti",
          bornOn: 1828,
          diedOn: 1882,
          gender: "male",
          placeOfBirth: "London",
          placeOfDeath: "Kent",
          nationality: "English",
          burialSite: "All Saints Church, Birchington",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Dante_Gabriel_Rossetti",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "John Everett",
          lastName: "Millais",
          knownAs: null,
          bornOn: 1829,
          diedOn: 1896,
          gender: "male",
          placeOfBirth: "Southampton",
          placeOfDeath: "London,",
          nationality: "English",
          burialSite: "St. Paul's Cathedral, London",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/John_Everett_Millais",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Bertrand",
          lastName: "Redon",
          knownAs: "Odilon Redon",
          bornOn: 1840,
          diedOn: 1916,
          gender: "male",
          placeOfBirth: "Bordeaux",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Bievres Communal Churchyard, Bievres",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Odilon_Redon",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Gustav",
          lastName: "Klimt",
          knownAs: null,
          bornOn: 1862,
          diedOn: 1918,
          gender: "male",
          placeOfBirth: "Baumgarten",
          placeOfDeath: "Vienna",
          nationality: "Austrian",
          burialSite: "Hietzing Cemetery, Vienna",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Gustav_Klimt",
          imageUrl: "https://www.gustav-klimt.com/images/klimt.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Egon",
          lastName: "Schiele",
          knownAs: null,
          bornOn: 1890,
          diedOn: 1918,
          gender: "male",
          placeOfBirth: "Tulln an der Donau",
          placeOfDeath: "Vienna",
          nationality: "Austrian",
          burialSite: "Cemetery Ober-Sankt-Veit, Vienna",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Egon_Schiele",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Édouard",
          lastName: "Manet",
          knownAs: null,
          bornOn: 1832,
          diedOn: 1883,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Passy Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/%C3%89douard_Manet",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/%C3%89douard_Manet-crop.jpg/343px-%C3%89douard_Manet-crop.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Oscar-Claude",
          lastName: "Monet",
          knownAs: "Claude Monet",
          bornOn: 1840,
          diedOn: 1926,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Giverny",
          nationality: "French",
          burialSite: "Giverny Church Cemetery, Giverny",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Claude_Monet",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Claude_Monet_1899_Nadar_crop.jpg/220px-Claude_Monet_1899_Nadar_crop.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Pierre-Auguste",
          lastName: "Renoir",
          knownAs: null,
          bornOn: 1841,
          diedOn: 1919,
          gender: "male",
          placeOfBirth: "Limoges",
          placeOfDeath: "Cagnes-sur-Mer",
          nationality: "French",
          burialSite: "Essoyes Cimetière, Essoyes,",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Pierre-Auguste_Renoir",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hilaire-Germain-Edgar",
          lastName: "De Gas",
          knownAs: "Edgar Degas",
          bornOn: 1834,
          diedOn: 1917,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Montmartre Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Edgar_Degas",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "François Auguste René",
          lastName: "Rodin",
          knownAs: "Auguste Rodin",
          bornOn: 1840,
          diedOn: 1917,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Meudon",
          nationality: "French",
          burialSite: "Musée Rodin, Meudon",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Auguste_Rodin",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "James Abbott",
          lastName: "McNeill Whistler",
          knownAs: null,
          bornOn: 1834,
          diedOn: 1903,
          gender: "male",
          placeOfBirth: "Lowell, MA",
          placeOfDeath: "London",
          nationality: "American",
          burialSite: "Old Chiswick Cemetery, London",
          painter: true,
          sculptor: false,
          wikiUrl:
            "https://en.wikipedia.org/wiki/James_Abbott_McNeill_Whistler",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paul",
          lastName: "Cézanne",
          knownAs: null,
          bornOn: 1839,
          diedOn: 1906,
          gender: "male",
          placeOfBirth: "Aix-en-Provence",
          placeOfDeath: "Aix-en-Provence",
          nationality: "French",
          burialSite: "Saint-Pierre Cemetery, Aix-en-Provence",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Paul_C%C3%A9zanne",
          imageUrl:
            "https://impress.wag.ca/uploads/ck/images/impressionists/Paul_Cezanne_b_500px.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Georges-Pierre",
          lastName: "Seurat",
          knownAs: "Georges Seurat",
          bornOn: 1859,
          diedOn: 1891,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Georges_Seurat",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Vincent Willem",
          lastName: "van Gogh",
          knownAs: "Vincent van Gogh",
          bornOn: 1853,
          diedOn: 1890,
          gender: "male",
          placeOfBirth: "Zundert",
          placeOfDeath: "Auvers-sur-Oise",
          nationality: "Dutch",
          burialSite: "Auvers-sur-Oise Town Cemetery, Auvers-sur-Oise",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Vincent_van_Gogh",
          imageUrl:
            "https://external-preview.redd.it/qXWbWLRjCmmy8y_i4zTEHf8hHcaNTBiRXRspIwWghSI.jpg?auto=webp&s=ee8d2f2519bf6f0683461c55007afa3b4a9f9b8f",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Eugène Henri Paul",
          lastName: "Gauguin",
          knownAs: "Paul Gauguin",
          bornOn: 1848,
          diedOn: 1903,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Atuona, Marquesas Islands",
          nationality: "French",
          burialSite: "Calvary Cemetery, Hiva-Oa",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Paul_Gauguin",
          imageUrl: "https://www.gauguin.org/images/gauguin.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Edvard",
          lastName: "Munch",
          knownAs: null,
          bornOn: 1863,
          diedOn: 1944,
          gender: "male",
          placeOfBirth: "Ådalsbruk",
          placeOfDeath: "Oslo",
          nationality: "Norwegian",
          burialSite: "Our Savior's Cemetery, Oslo",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Edvard_Munch",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Käthe",
          lastName: "Kollwitz",
          knownAs: null,
          bornOn: 1867,
          diedOn: 1945,
          gender: "male",
          placeOfBirth: "Kaliningrad",
          placeOfDeath: "Moritzburg",
          nationality: "German",
          burialSite: "Zentralfriedhof, Friedrichsfelde",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/K%C3%A4the_Kollwitz",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/9/9e/K%C3%A4the_Kollwitz_by_Hugo_Erfurth%2C_1927.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Wassily",
          lastName: "Wassilyevich Kandinsky",
          knownAs: "Wassily Kandinsky",
          bornOn: 1866,
          diedOn: 1944,
          gender: "male",
          placeOfBirth: "Moscow",
          placeOfDeath: "Neuilly-sur-Seine",
          nationality: "Russian",
          burialSite: "Neuilly-sur-Seine community cemetery, Neuilly-sur-Seine",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Wassily_Kandinsky",
          imageUrl:
            "https://singulart-website-prod.s3.eu-central-1.amazonaws.com/famous/artists/cropped/famous_artist_59_2e0c70c2adeb1ee55e2814445d876830.jpeg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Henri Julien Félix",
          lastName: "Rousseau",
          knownAs: "Henri Rousseau",
          bornOn: 1844,
          diedOn: 1910,
          gender: "male",
          placeOfBirth: "Laval",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Cimetière de Bagneux, Bagneux",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Henri_Rousseau",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/f/fc/Rousseau_Joyeux_Farceurs_Dornac_crop.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Henri Émile Benoît",
          lastName: "Matisse",
          knownAs: "Henri Matisse",
          bornOn: 1869,
          diedOn: 1954,
          gender: "male",
          placeOfBirth: "Le Cateau-Cambrésis",
          placeOfDeath: "Nice",
          nationality: "French",
          burialSite: "Cimiez Cemetery and Monastery, Cimiez",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Henri_Matisse",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/b/b1/Portrait_of_Henri_Matisse_1933_May_20.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "James Sidney Edouard",
          lastName: "Ensor",
          knownAs: "James Ensor",
          bornOn: 1860,
          diedOn: 1949,
          gender: "male",
          placeOfBirth: "Ostend",
          placeOfDeath: "Ostend",
          nationality: "Belgian",
          burialSite: "Onze-Lieve-Vrouw-ter-Duinenkerk, Ostend",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/James_Ensor",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Pablo Diego José Francisco",
          lastName:
            "de Paula Juan Nepomuceno María de los Remedios Cipriano de la Santísima Trinidad Ruiz y Picasso",
          knownAs: "Pablo Picasso",
          bornOn: 1881,
          diedOn: 1973,
          gender: "male",
          placeOfBirth: "Malaga",
          placeOfDeath: "Mougins",
          nationality: "Spanish",
          burialSite: "Château of Vauvenargues, Vauvenargues",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Ch%C3%A2teau_of_Vauvenargues",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Pablo_picasso_1.jpg/653px-Pablo_picasso_1.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Georges",
          lastName: "Braque",
          knownAs: null,
          bornOn: 1882,
          diedOn: 1963,
          gender: "male",
          placeOfBirth: "Argenteuil",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite:
            "Cimetière marin de Varengeville-sur-Mer, Varengeville-sur-Mer",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Georges_Braque",
          imageUrl: "https://www.georgesbraque.net/Georges%20Braque.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Umberto",
          lastName: "Boccioni",
          knownAs: null,
          bornOn: 1882,
          diedOn: 1916,
          gender: "male",
          placeOfBirth: "Reggio Calabria",
          placeOfDeath: "Verona",
          nationality: "Italian",
          burialSite: "Cimitero Monumentale, Verona",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Umberto_Boccioni",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/b/ba/Umberto_Boccioni%2C_portrait_photograph.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "František",
          lastName: "Kupka",
          knownAs: null,
          bornOn: 1871,
          diedOn: 1957,
          gender: "male",
          placeOfBirth: "Opočno",
          placeOfDeath: "Puteaux",
          nationality: "Czech",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Franti%C5%A1ek_Kupka",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Frantisek_Kupka_1928.jpg/467px-Frantisek_Kupka_1928.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Robert",
          lastName: "Delaunay",
          knownAs: null,
          bornOn: 1885,
          diedOn: 1941,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Montpellier",
          nationality: "French",
          burialSite: "Cimetière de Gambais, Gambais",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Robert_Delaunay",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Kazimir",
          lastName: "Severinovich Malevich",
          knownAs: "Kazimir Malevich",
          bornOn: 1879,
          diedOn: 1935,
          gender: "male",
          placeOfBirth: "Kiev",
          placeOfDeath: "Leningrad",
          nationality: "Russian",
          burialSite: "Nemchinovka, Moscow",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Kazimir_Malevich",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paul",
          lastName: "Klee",
          knownAs: null,
          bornOn: 1879,
          diedOn: 1940,
          gender: "male",
          placeOfBirth: "Münchenbuchsee",
          placeOfDeath: "",
          nationality: "Swiss",
          burialSite: "Muralto",
          painter: true,
          sculptor: false,
          wikiUrl: "Schosshalden cemetery, Bern",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Paul_Klee_1911.jpg/347px-Paul_Klee_1911.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ernst Ludwig",
          lastName: "Kirchner",
          knownAs: null,
          bornOn: 1880,
          diedOn: 1938,
          gender: "male",
          placeOfBirth: "Aschaffenburg",
          placeOfDeath: "Frauenkirch-Wildboden",
          nationality: "German",
          burialSite: "Munich Waldfriedhof, Munich",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Ernst_Ludwig_Kirchner",
          imageUrl:
            "https://artlogic-res.cloudinary.com/c_limit,f_auto,fl_lossy/ws-pelham/usr/library/main/images/kirchner.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Henri-Robert-Marcel",
          lastName: "Duchamp",
          knownAs: "Marcel Duchamp",
          bornOn: 1887,
          diedOn: 1968,
          gender: "male",
          placeOfBirth: "Blainville-Crevon",
          placeOfDeath: "Neuilly-sur-Seine",
          nationality: "French",
          burialSite: "Rouen Cemetery, Rouen",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Marcel_Duchamp",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/e/e2/Marcel_Duchamp_01.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Constantin",
          lastName: "Brâncuși",
          knownAs: null,
          bornOn: 1867,
          diedOn: 1957,
          gender: "male",
          placeOfBirth: "Hobița",
          placeOfDeath: "Paris",
          nationality: "Romanian",
          burialSite: "Montparnasse Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl:
            "https://en.wikipedia.org/wiki/Constantin_Br%C3%A2ncu%C8%99i",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Edward_Steichen_-_Brancusi.jpg/580px-Edward_Steichen_-_Brancusi.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Pieter Cornelis",
          lastName: "Mondriaan",
          knownAs: "Piet Mondrian",
          bornOn: 1872,
          diedOn: 1944,
          gender: "male",
          placeOfBirth: "Amersfoort",
          placeOfDeath: "New York",
          nationality: "Dutch",
          burialSite: "Cypress Hills Cemetery, New York",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Piet_Mondrian",
          imageUrl:
            "https://236izu11yygk2uo6po3yerii7d6-wpengine.netdna-ssl.com/wp-content/uploads/2017/07/Piet_Mondrian_2-350x350.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Francis-Marie",
          lastName: "Martinez de Picabia",
          knownAs: "Francis Picabia",
          bornOn: 1879,
          diedOn: 1953,
          gender: "male",
          placeOfBirth: "Paris",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "Montmartre Cemetery, Paris",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Francis_Picabia",
          imageUrl:
            "https://lh3.googleusercontent.com/proxy/slWtO8kBzmXiY0PdsSqR-1H64F9qmeapSCtccRe9arBcn3XbrUZqd_W94VAJinquGT7Nwhv5De-nQRYJdS1DnbGdEkNuHSyIb5llENlpYnF4EVP8woxsTBI",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Max",
          lastName: "Ernst",
          knownAs: null,
          bornOn: 1891,
          diedOn: 1976,
          gender: "male",
          placeOfBirth: "Brühl",
          placeOfDeath: "Paris",
          nationality: "German",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Max_Ernst",
          imageUrl:
            "https://www.wienerzeitung.at/_em_daten/_cache/image/1x2km9EiulDsS_7BprPyUUJkwsPpLVKJejMkwvi_iYkW0bE98AFJM9CqwPmGpqOAD5Aj2k8Uo1_QkA_DQsFsACBiQGhSKvDP4ZY1k2kdJ81kU/160401-1205-948-0900-25206-0204eernst.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Hans Peter Wilhelm",
          lastName: "Arp",
          knownAs: "Jean Arp",
          bornOn: 1886,
          diedOn: 1966,
          gender: "male",
          placeOfBirth: "Strasbourg",
          placeOfDeath: "Basel",
          nationality: "German-French",
          burialSite: "Cimitero di Locarno, Locarno",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean_Arp",
          imageUrl:
            "https://cdn.shopify.com/s/files/1/1079/6284/files/Jean_Arp_portrait_large.jpg?v=1505584704",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joan",
          lastName: "Miró i Ferrà",
          knownAs: "Joan Miró",
          bornOn: 1893,
          diedOn: 1983,
          gender: "male",
          placeOfBirth: "Barcelona",
          placeOfDeath: "Palma de Mallorca",
          nationality: "Spanish",
          burialSite: "Montjuïc Cemetery, Barcelona",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Joan_Mir%C3%B3",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Alexander",
          lastName: "Calder",
          knownAs: null,
          bornOn: 1898,
          diedOn: 1976,
          gender: "male",
          placeOfBirth: "Lawnton, PA",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Unknown",
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Alexander_Calder",
          imageUrl:
            "https://uploads3.wikiart.org/00207/images/alexander-calder/1-be288c121dfe8dc4489b58e4256b3fba.jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Dame Jocelyn Barbara",
          lastName: "Hepworth",
          knownAs: "Barbara Hepworth",
          bornOn: 1903,
          diedOn: 1975,
          gender: "male",
          placeOfBirth: "Wakefield",
          placeOfDeath: "St Ives",
          nationality: "English",
          burialSite: "Longstone Cemetery, Carbis Bay",
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Barbara_Hepworth",
          imageUrl:
            "https://collectionimages.npg.org.uk/large/mw113039/Barbara-Hepworth.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Moïche Zakharovitch",
          lastName: "Chagalov",
          knownAs: "Marc Chagall",
          bornOn: 1887,
          diedOn: 1985,
          gender: "male",
          placeOfBirth: "Liozna",
          placeOfDeath: "Saint-Paul-de-Vence",
          nationality: "Russian",
          burialSite: "Saint Paul de Vence Cemetery, Saint Paul de Vence",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Marc_Chagall",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Edward",
          lastName: "Hopper",
          knownAs: null,
          bornOn: 1882,
          diedOn: 1967,
          gender: "male",
          placeOfBirth: "Nyack, NY",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Oak Hill Cemetery, Nyack, NY",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Edward_Hopper",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Grant",
          lastName: "DeVolson Wood",
          knownAs: "Grant Wood",
          bornOn: 1891,
          diedOn: 1942,
          gender: "male",
          placeOfBirth: "Anamosa, IA",
          placeOfDeath: "Iowa City, IA",
          nationality: "American",
          burialSite: "Riverside Cemetery, Anamosa, IA",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Grant_Wood",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Giorgio",
          lastName: "de Chirico",
          knownAs: null,
          bornOn: 1888,
          diedOn: 1978,
          gender: "male",
          placeOfBirth: "Volos",
          placeOfDeath: "Rome",
          nationality: "Italian",
          burialSite: "Chiesa di San Francesco a Ripa Grande, Rome",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Giorgio_de_Chirico",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "René François",
          lastName: "Ghislain Magritte",
          knownAs: "René Magritte",
          bornOn: 1898,
          diedOn: 1967,
          gender: "male",
          placeOfBirth: "Lessines",
          placeOfDeath: "Brussels",
          nationality: "Belgian",
          burialSite: "Communal cemetery Schaerbeek, Evere",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Ren%C3%A9_Magritte",
          imageUrl:
            "https://www.moma.org/d/assets/W1siZiIsIjIwMTgvMDEvMjMvOHg0dXM3dm16dl9BUkNIXzc4MTZfRnVsbF9KUEVHX2Nyb3BfbmV3LmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDUxMng1MTJcdTAwM2UiXV0/ARCH_7816-Full_JPEG-crop%20new.jpg?sha=6db672aa000e6b4a",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Salvador Domingo Felipe Jacinto",
          lastName: "Dalí i Domènech",
          knownAs: "Salvador Dalí",
          bornOn: 1904,
          diedOn: 1989,
          gender: "male",
          placeOfBirth: "Figueres",
          placeOfDeath: "Figueres",
          nationality: "Spanish",
          burialSite: "Dalí Theatre and Museum, Figueres",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Salvador_Dal%C3%AD",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          firstName: "Dorothea Margaret",
          lastName: "Tanning",
          knownAs: "Dorothea Tanning",
          bornOn: 1910,
          diedOn: 2012,
          gender: "female",
          placeOfBirth: "Galesburg, IL",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Dorothea_Tanning",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Diego María de la Concepción Juan Nepomuceno Estanislao",
          lastName: "de la Rivera y Barrientos Acosta y Rodríguez",
          knownAs: "Diego Rivera",
          bornOn: 1886,
          diedOn: 1957,
          gender: "male",
          placeOfBirth: "Guanajuato City",
          placeOfDeath: "Mexico City",
          nationality: "Mexican",
          burialSite: "Panteón de Dolores, Mexico City",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Diego_Rivera",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Magdalena Carmen Frida",
          lastName: "Kahlo y Calderón",
          knownAs: "Frida Kahlo",
          bornOn: 1907,
          diedOn: 1954,
          gender: "female",
          placeOfBirth: "Mexico City",
          placeOfDeath: "Mexico City",
          nationality: "Mexican",
          burialSite:
            "Londres St. in Coayocan (urn at her home address), Mexico",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Frida_Kahlo",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg/320px-Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Georgia",
          lastName: "Totto O'Keeffe",
          knownAs: "Georgia O'Keeffe",
          bornOn: 1887,
          diedOn: 1986,
          gender: "female",
          placeOfBirth: "Sun Prairie, WI",
          placeOfDeath: "Santa Fe, NM",
          nationality: "American",
          burialSite: "Ashes scattered at The Pedernal, New Mexico",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Georgia_O%27Keeffe",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Markus",
          lastName: "Yakovlevich Rothkowitz",
          knownAs: "Mark Rothko",
          bornOn: 1903,
          diedOn: 1970,
          gender: "male",
          placeOfBirth: "Daugavpils",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "East Marion Cemetery, East Marion, NY",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Mark_Rothko",
          imageUrl: "https://contemporary.co.il/art/damien-hirst.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Paul",
          lastName: "Jackson Pollock",
          knownAs: "Jackson Pollock",
          bornOn: 1912,
          diedOn: 1956,
          gender: "male",
          placeOfBirth: "Cody, WY",
          placeOfDeath: "Springs, NY",
          nationality: "American",
          burialSite: "Green River Cemetery, Springs, NY",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jackson_Pollock",
          imageUrl:
            "https://1.bp.blogspot.com/-xXuw8AROBB4/UuEC6Ca70PI/AAAAAAAACS8/QYHoVv6KeXY/s1600/artist-Jackson-Pollock-3.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Willem",
          lastName: "de Kooning",
          knownAs: null,
          bornOn: 1904,
          diedOn: 1997,
          gender: "male",
          placeOfBirth: "Rotterdam",
          placeOfDeath: "East Hampton",
          nationality: "Dutch-American",
          burialSite: "Unknown",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Willem_de_Kooning",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Yves",
          lastName: "Klein",
          knownAs: null,
          bornOn: 1928,
          diedOn: 1962,
          gender: "male",
          placeOfBirth: "Nice",
          placeOfDeath: "Paris",
          nationality: "French",
          burialSite: "La Colle-sur-Loup Cemetery, La Colle-sur-Loup",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Yves_Klein",
          imageUrl:
            "https://anniversaire-celebrite.com/upload/250x333/yves-klein-250.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Joseph",
          lastName: "Beuys",
          knownAs: null,
          bornOn: 1921,
          diedOn: 1986,
          gender: "male",
          placeOfBirth: "Krefeld",
          placeOfDeath: "Düsseldorf",
          nationality: "German",
          burialSite: "Cremated, ashes scatterd at Nordsee",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Joseph_Beuys",
          imageUrl:
            "https://www.tate.org.uk/sites/default/files/styles/width-420/public/images/beu_contact3_lg.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Francis",
          lastName: "Bacon",
          knownAs: null,
          bornOn: 1909,
          diedOn: 1992,
          gender: "male",
          placeOfBirth: "Dublin",
          placeOfDeath: "Madrid",
          nationality: "English",
          burialSite: "Cremated, Ashes given to family or friend",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Francis_Bacon_(artist)",
          imageUrl:
            "https://bookstore.antrodiulisse.eu/wp-content/uploads/2011/04/Bacon_3.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Andrew",
          lastName: "Warhola",
          knownAs: "Andy Warhol",
          bornOn: 1928,
          diedOn: 1987,
          gender: "male",
          placeOfBirth: "Pittsburgh, PA",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite:
            "St. John the Baptist Byzantine Catholic Cemetery, Bethel Park, PA",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Andy_Warhol",
          imageUrl:
            "https://media.mutualart.com/Images/2011_06/09/10/105518974/4aff3fea-0e07-4ee0-a5d7-25a2e40c635d_570.Jpeg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jean-Michel",
          lastName: "Basquiat",
          knownAs: null,
          bornOn: 1960,
          diedOn: 1988,
          gender: "male",
          placeOfBirth: "New York City, NY",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Green-Wood Cemetery, Brooklyn, NY",
          painter: true,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Jean-Michel_Basquiat",
          imageUrl:
            "https://uploads3.wikiart.org/images/jean-michel-basquiat.jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Roy Fox",
          lastName: "Lichtenstein[",
          knownAs: "Roy Lichtenstein",
          bornOn: 1923,
          diedOn: 1997,
          gender: "male",
          placeOfBirth: "New York City, NY",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Cremated, Ashes given to family or friend",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Roy_Lichtenstein",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Allan",
          lastName: "Kaprow",
          knownAs: null,
          bornOn: 1927,
          diedOn: 2006,
          gender: "male",
          placeOfBirth: "Atlantic City, NJ",
          placeOfDeath: "Encinitas, CA",
          nationality: "American",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Allan_Kaprow",
          imageUrl:
            "https://upload.wikimedia.org/wikipedia/commons/6/6c/Allan_Kaprow.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Christiaan Karel",
          lastName: "Appel",
          knownAs: "Karel Appel",
          bornOn: 1921,
          diedOn: 2006,
          gender: "male",
          placeOfBirth: "Amsterdam",
          placeOfDeath: "Zürich",
          nationality: "Dutch",
          burialSite: "Père Lachaise Cemetery, Paris",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Karel_Appel",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Nam June",
          lastName: "Paik",
          knownAs: null,
          bornOn: 1932,
          diedOn: 2006,
          gender: "male",
          placeOfBirth: "Seoul",
          placeOfDeath: "Miami, FL",
          nationality: "Korean-American",
          burialSite: "Cremated, ashes spread in many different locations",
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Nam_June_Paik",
          imageUrl:
            "https://m.theartstory.org/images20/new_design/bio/bio_paik_nam_june.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Donald Clarence",
          lastName: "Judd",
          knownAs: "Donald Judd",
          bornOn: 1928,
          diedOn: 1994,
          gender: "male",
          placeOfBirth: "Excelsior Springs, MO",
          placeOfDeath: "New York City, NY",
          nationality: "American",
          burialSite: "Judd Ranch, Marfa, TX",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Donald_Judd",
          imageUrl:
            "https://uploads6.wikiart.org/images/donald-judd(1).jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Louise Joséphine",
          lastName: "Bourgeois",
          knownAs: "Louise Bourgeois",
          bornOn: 1911,
          diedOn: 2010,
          gender: "female",
          placeOfBirth: "Paris",
          placeOfDeath: "New York City, NY",
          nationality: "French-American",
          burialSite: "Cutchogue Cemetery, Cutchogue, NY",
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Louise_Bourgeois",
          imageUrl:
            "https://1.bp.blogspot.com/-J61qvCCG0vY/XSqU5tDGfcI/AAAAAAACHss/WaWQRhhz8zw9eRTZH80vEo93oEPT6gkQgCLcBGAs/s1600/Louise%2BBourgeois2.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Edwin Parker Cy",
          lastName: "Twombly",
          knownAs: "Cy Twombly",
          bornOn: 1928,
          diedOn: 2011,
          gender: "male",
          placeOfBirth: "Lexington, VI",
          placeOfDeath: "Rome",
          nationality: "American",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Cy_Twombly",
          imageUrl:
            "https://i.guim.co.uk/img/static/Guardian/culture/gallery/2008/jun/03/twombly/twombly-2825.jpg?width=700&quality=85&auto=format&fit=max&s=82972a53253b810eb939cf4bb011ef9e",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Arnaldo",
          lastName: "Pomodoro",
          knownAs: null,
          bornOn: 1926,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Morciano",
          placeOfDeath: null,
          nationality: "Italian",
          burialSite: null,
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Arnaldo_Pomodoro",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Claes",
          lastName: "Oldenburg",
          knownAs: null,
          bornOn: 1929,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Stockholm",
          placeOfDeath: null,
          nationality: "Swedish-American",
          burialSite: null,
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Claes_Oldenburg",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        {
          firstName: "Gerhard",
          lastName: "Richter",
          knownAs: null,
          bornOn: 1932,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Dresden",
          placeOfDeath: null,
          nationality: "German",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Gerhard_Richter",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Yoko",
          lastName: "Ono Lennon",
          knownAs: "Yoko Ono",
          bornOn: 1933,
          diedOn: null,
          gender: "female",
          placeOfBirth: "Tokyo",
          placeOfDeath: null,
          nationality: "Japanese",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Yoko_Ono",
          imageUrl:
            "https://www.cambridgenetwork.co.uk/sites/default/files/Yoko%20Ono.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Richard",
          lastName: "Serra",
          knownAs: null,
          bornOn: 1938,
          diedOn: null,
          gender: "male",
          placeOfBirth: "San Francisco, CA",
          placeOfDeath: null,
          nationality: "American",
          burialSite: null,
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Richard_Serra",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Barbara",
          lastName: "Kruger",
          knownAs: null,
          bornOn: 1945,
          diedOn: null,
          gender: "female",
          placeOfBirth: "Newark, NJ",
          placeOfDeath: null,
          nationality: "American",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Barbara_Kruger",
          imageUrl:
            "https://www.theartstory.org/images20/photo/kruger_barbara_2.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Anselm",
          lastName: "Kiefer",
          knownAs: null,
          bornOn: 1945,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Donaueschingen",
          placeOfDeath: null,
          nationality: "German",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Anselm_Kiefer",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Marina",
          lastName: "Abramović",
          knownAs: null,
          bornOn: 1946,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Belgrade",
          placeOfDeath: null,
          nationality: "Serbian",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl:
            "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Karel_Appel_%281982%29.jpg/360px-Karel_Appel_%281982%29.jpg",
          imageUrl:
            "https://uploads4.wikiart.org/00215/images//marina-abramovi-the-artist-is-present-viennale-2012-cropped.jpg!Portrait.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Bill",
          lastName: "Viola",
          knownAs: null,
          bornOn: 1951,
          diedOn: null,
          gender: "male",
          placeOfBirth: "New York City, NY",
          placeOfDeath: null,
          nationality: "American",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Bill_Viola",
          imageUrl:
            "https://res.cloudinary.com/opera-national-de-paris/image/upload/c_crop%2Ch_2500%2Cw_3746%2Cx_0%2Cy_0/c_fit%2Ch_435%2Cw_770/f_auto/v1/user_photos/uao2aknxb45xtdqtwvvs",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Jeffrey L.",
          lastName: "Koons",
          knownAs: "Jeff Koons",
          bornOn: 1955,
          diedOn: null,
          gender: "male",
          placeOfBirth: "York, PA",
          placeOfDeath: null,
          nationality: "American",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Jeff_Koons",
          imageUrl:
            "https://news.artnet.com/app/news-upload/2019/02/4448-0024-683x1024.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Ai",
          lastName: "Weiwei",
          knownAs: null,
          bornOn: 1957,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Beijing",
          placeOfDeath: null,
          nationality: "Chinese",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Ai_Weiwei",
          imageUrl:
            "https://media.timeout.com/images/105183585/630/472/image.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Maurizio",
          lastName: "Cattelan",
          knownAs: null,
          bornOn: 1960,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Padua",
          placeOfDeath: null,
          nationality: "Italian",
          burialSite: null,
          painter: false,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Maurizio_Cattelan",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Tracey",
          lastName: "Emin",
          knownAs: null,
          bornOn: 1963,
          diedOn: null,
          gender: "female",
          placeOfBirth: "Croydon",
          placeOfDeath: null,
          nationality: "English",
          burialSite: null,
          painter: false,
          sculptor: false,
          wikiUrl: "https://en.wikipedia.org/wiki/Tracey_Emin",
          imageUrl: "",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: "Damien",
          lastName: "Hirst",
          knownAs: null,
          bornOn: 1965,
          diedOn: null,
          gender: "male",
          placeOfBirth: "Bristol",
          placeOfDeath: null,
          nationality: "English",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Damien_Hirst",
          imageUrl: "https://contemporary.co.il/art/damien-hirst.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          firstName: null,
          lastName: "Unknown",
          knownAs: "Banksy",
          bornOn: 1974,
          diedOn: null,
          gender: null,
          placeOfBirth: "Bristol",
          placeOfDeath: null,
          nationality: "English",
          burialSite: null,
          painter: true,
          sculptor: true,
          wikiUrl: "https://en.wikipedia.org/wiki/Banksy",
          imageUrl:
            "https://www.martinimanna.com/wp-content/uploads/2019/03/45087774_2156020357947031_2754511158563045376_n.jpg",
          bio: "",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("artists", null, {});
  },
};
